Add kubestash controller for changing kubeDB phase
kubedb/apimachinery pull request #1076
Opened 2023-11-28 09:27 UTC by anisurrahman75

Signed-off-by: Anisur Rahman <anisur@appscode.com>

2023-11-28 09:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/apimachinery?pullRequest=1076) it.</sub>

2023-11-28 12:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/apimachinery?pullRequest=1076) it.</sub>

2023-11-29 10:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/apimachinery?pullRequest=1076) it.</sub>

2023-11-29 11:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1076) before we can accept your contribution.<br/><hr/>**Anisur Rahman** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/apimachinery?pullRequest=1076) it.</sub>

2023-12-12 06:11 UTC, hmsayem requested changes

2023-12-12 06:11 UTC, hmsayem commented on pkg/controller/initializer/restore/util.go
> +			appBinding, err := c.AppCatalogClient.AppcatalogV1alpha1().AppBindings(ri.do.Namespace).Get(context.TODO(), ri.stashTarget.Ref.Name, metav1.GetOptions{})
remove `ri.kubeStashTarget != nil` if not necessary

2023-12-12 06:11 UTC, hmsayem commented on pkg/controller/initializer/restore/util.go
> +			if err != nil {
`ri.do.Namespace` should be replaced with `ri.kubeStashTarget.Namespace`

2023-12-14 09:23 UTC, ishtiaqhimel submitted a review, later dismissed

2023-12-14 09:38 UTC, hmsayem requested changes

2023-12-14 09:38 UTC, hmsayem commented on pkg/controller/initializer/restore/util.go
> +			schema.GroupKind{Group: coreapi.GroupVersion.Group, Kind: coreapi.ResourceKindRestoreSession},
Add RetentionPolicy

2023-12-20 06:07 UTC, ArnobKumarSaha requested changes

2023-12-20 06:07 UTC, ArnobKumarSaha commented on pkg/controller/initializer/restore/controller.go
> +	kubeStashPhase  coreapi.RestorePhase
We should make this struct more organized . like 
```
type restoreInfo struct {
	invoker     core.TypedLocalObjectReference
	stash       *stashInfo
	kubestash   *kubestashInfo
	do          dmcond.DynamicOptions
	invokerUID  types.UID
}

type stashInfo struct {
	target *v1beta1.RestoreTarget
	phase v1beta1.RestorePhase
}

type kubestashInfo struct {
	target *kmapi.TypedObjectReference
	phase coreapi.RestorePhase
}
```

2023-12-22 09:02 UTC, ArnobKumarSaha approved these changes

2023-12-22 09:03 UTC, merged