Add ZooKeeper API
kubedb/apimachinery pull request #1104
Opened 2024-01-10 11:03 UTC by AbdullahAlShaad

2024-01-16 08:39 UTC, ArnobKumarSaha requested changes

2024-01-17 06:01 UTC, AbdullahAlShaad commented on apis/kubedb/v1alpha2/zookeeper_webhook.go
> +// log is for logging in this package.
Removed todo comments

2024-01-17 06:01 UTC, AbdullahAlShaad commented on apis/kubedb/v1alpha2/zookeeper_helpers.go
> +func (z *ZooKeeper) GetPersistentSecrets() []string {
Will return all the secret from this func. For now, its just auth secret.

2024-01-17 09:35 UTC, ArnobKumarSaha approved these changes

2024-01-17 09:54 UTC, merged