Add Rabbitmq API
kubedb/apimachinery pull request #1109
Opened 2024-01-16 05:53 UTC by raihankhan

2024-01-17 08:36 UTC, AbdullahAlShaad requested changes

2024-01-17 08:36 UTC, AbdullahAlShaad commented on apis/kubedb/v1alpha2/rabbitmq_webhook.go
> +	version := db.Spec.Version
Instead of mainting a static list, dynamically get the version to check its existance.

2024-01-17 08:36 UTC, AbdullahAlShaad commented on apis/kubedb/v1alpha2/rabbitmq_types.go
> +	StorageType StorageType `json:"storageType,omitempty"`
Not needed. Not used anywhere.

2024-01-17 08:36 UTC, AbdullahAlShaad commented on apis/kubedb/v1alpha2/kafka_webhook.go
>  		if v == version {
Remove static check

2024-01-19 11:15 UTC, ArnobKumarSaha approved these changes

2024-01-19 11:15 UTC, merged