Add MS SQL Ops Requests
kubedb/apimachinery pull request #1198
Opened 2024-04-22 11:27 UTC by Neaj-Morshad-101

2024-09-23 14:11 UTC, Neaj-Morshad-101 commented on apis/kubedb/constants.go
> +			core.ResourceCPU:    resource.MustParse("2000m"),
will remove this

2024-09-24 06:28 UTC, souravbiswassanto approved these changes

2024-09-24 09:25 UTC, ArnobKumarSaha requested changes

2024-09-24 09:25 UTC, ArnobKumarSaha commented on apis/kubedb/constants.go
> +	DefaultResourcesMemoryIntensiveMSSQLServer = core.ResourceRequirements{
Remove this.  Use `DefaultResourcesMemoryIntensive`.  Update the comment

2024-09-24 10:06 UTC, ArnobKumarSaha approved these changes

2024-09-24 10:06 UTC, merged