Add Pgpool TLS
kubedb/apimachinery pull request #1199
Opened 2024-04-25 09:28 UTC by MobarakHsn

2024-04-25 12:53 UTC, ArnobKumarSaha requested changes

2024-04-25 12:53 UTC, ArnobKumarSaha commented on apis/kubedb/v1alpha2/pgpool_types.go
> +	// ClientAuthMode for sidecar or sharding. (default will be md5. [md5;scram;cert])
Use marker
`// +kubebuilder:default=md5`

2024-04-25 12:53 UTC, ArnobKumarSaha commented on apis/kubedb/v1alpha2/pgpool_helpers.go
> +		}
Remove clientAuthMode parts, as we are defaulting with marker now.

2024-04-25 12:53 UTC, ArnobKumarSaha commented on apis/kubedb/v1alpha2/pgpool_helpers.go
> +		return "disable", nil
return PgpoolSSLModeDisable, nil

2024-04-25 12:53 UTC, ArnobKumarSaha commented on apis/kubedb/v1alpha2/pgpool_helpers.go
> +}
Why this ? `GetCertSecretName()` not enough ?

2024-04-25 14:28 UTC, souravbiswassanto requested changes

2024-04-25 14:28 UTC, souravbiswassanto commented on apis/kubedb/v1alpha2/pgpool_helpers.go
> +	sslmodeString := appBinding.Spec.ClientConfig.Service.Query
Guess you should give nill check

2024-04-26 04:14 UTC, ArnobKumarSaha requested changes

2024-04-26 04:14 UTC, ArnobKumarSaha commented on apis/kubedb/v1alpha2/pgpool_helpers.go
> +	return false, nil
Just this should be enough
```
	return apb.Spec.TLSSecret != nil || len(apb.Spec.ClientConfig.CABundle) > 0 || sslMode != PgpoolSSLModeDisable, nil
```

2024-04-26 04:14 UTC, ArnobKumarSaha commented on apis/kubedb/v1alpha2/pgpool_helpers.go
> +}
`return PgpoolSSLMode(strings.TrimSpace(temps[1])), nil`

2024-04-26 04:44 UTC, ArnobKumarSaha approved these changes

2024-04-26 05:05 UTC, souravbiswassanto approved these changes

2024-04-26 05:10 UTC, merged