Add Pgpool OpsRequest API
kubedb/apimachinery pull request #1209
Opened 2024-05-08 08:41 UTC by MobarakHsn

Signed-off-by: MobarakHsn <mobarak@appscode.com>

2024-05-30 05:21 UTC, souravbiswassanto requested changes

2024-05-30 05:21 UTC, souravbiswassanto commented on apis/kubedb/v1alpha2/pgpool_webhook.go
> +		errorList = append(errorList, field.Invalid(field.NewPath("spec").Child("configSecret"),
replace || conditon to && condition

2024-05-30 05:21 UTC, souravbiswassanto commented on apis/kubedb/v1alpha2/pgpool_webhook.go
> +			Namespace: p.Spec.PostgresRef.Namespace,
use pgpool namespace

2024-05-30 05:21 UTC, souravbiswassanto commented on apis/ops/v1alpha1/pgpool_ops_types.go
> +type PgpoolReplicaReadinessCriteria struct{}
remove this

2024-05-31 05:09 UTC, souravbiswassanto submitted a review, later dismissed

2024-05-31 06:44 UTC, ArnobKumarSaha approved these changes

2024-05-31 06:44 UTC, merged