Add ZooKeeper Ops Request
kubedb/apimachinery pull request #1263
Opened 2024-07-17 10:38 UTC by AbdullahAlShaad

2024-07-26 08:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/kubedb/apimachinery?pullRequest=1263) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: AbdullahAlShaad<br/>:x: Rudro-25<br/><hr/>**Rudro-25** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kubedb/apimachinery?pullRequest=1263) it.</sub>

2024-08-13 06:18 UTC, raihankhan requested changes
Fix comments. comments have references to rabbitmq, druid etc.

2024-08-13 06:21 UTC, raihankhan requested changes

2024-08-13 06:21 UTC, raihankhan commented on apis/ops/v1alpha1/zookeeper_ops_helpers.go
> +func (s *ZooKeeperOpsRequest) CustomResourceDefinition() *apiextensions.CustomResourceDefinition {
Maybe use `z *ZooKeeperOpsRequest` as receiver.

2024-08-13 06:21 UTC, raihankhan commented on apis/ops/v1alpha1/zookeeper_ops_types.go
> +// ENUM(UpdateVersion, HorizontalScaling, VerticalScaling, VolumeExpansion, Restart, Reconfigure)
Remove Horizontal scaling and Reconfigure froim enum if not added in this PR.

2024-09-05 08:41 UTC, AbdullahAlShaad commented
Sign CLA

2024-09-24 06:07 UTC, merged