pgbouncer autoScaler added in scheme register
kubedb/apimachinery pull request #1268
Opened 2024-07-30 05:33 UTC by HiranmoyChowdhury

Signed-off-by: Hiranmoy Das Chowdhury <hiranmoy@appscode.com>

2024-07-30 06:46 UTC, MobarakHsn submitted a review, later dismissed

2024-07-30 07:07 UTC, ArnobKumarSaha requested changes

2024-07-30 07:07 UTC, ArnobKumarSaha commented on apis/autoscaling/v1alpha1/register.go
> +		&PgBouncerAutoscalerList{},
Add all the other autoscaler types too.  seems, Many of them are missing.

2024-07-30 08:41 UTC, ArnobKumarSaha commented on apis/autoscaling/v1alpha1/register.go
> +		&PgBouncerAutoscalerList{},
Nope.  Compare with this list : https://github.com/kubedb/apimachinery/tree/master/apis/autoscaling/v1alpha1

2024-08-01 14:07 UTC, ArnobKumarSaha approved these changes

2024-08-01 14:07 UTC, merged