version update of pgbouncer
kubedb/apimachinery pull request #1284
Opened 2024-08-13 10:04 UTC by HiranmoyChowdhury

Signed-off-by: Hiranmoy Das Chowdhury <hiranmoy@appscode.com>

2024-08-21 12:38 UTC, obaydullahmhs requested changes

2024-08-21 12:38 UTC, obaydullahmhs commented on apis/catalog/v1alpha1/pgbouncer_version_helpers.go
> +func (p PgBouncerVersion) IsDepricated() bool {
fixed the spelling `IsDeprecated`

2024-08-21 12:59 UTC, obaydullahmhs commented on apis/ops/v1alpha1/pgbouncer_ops_helpers.go
> +}
You should move these type of function to `ops-manager` repo

2024-09-05 05:16 UTC, HiranmoyChowdhury commented on apis/catalog/v1alpha1/pgbouncer_version_helpers.go
> +func (p PgBouncerVersion) IsDepricated() bool {
done

2024-09-05 09:34 UTC, obaydullahmhs approved these changes

2024-09-06 05:17 UTC, ArnobKumarSaha approved these changes

2024-09-06 05:17 UTC, merged