Persist mssql config secret
kubedb/apimachinery pull request #1322
Opened 2024-10-07 12:37 UTC by Neaj-Morshad-101

2024-10-08 12:24 UTC, souravbiswassanto submitted a review, later dismissed

2024-10-15 12:23 UTC, souravbiswassanto requested changes

2024-10-15 12:43 UTC, Neaj-Morshad-101 commented on apis/kubedb/v1alpha2/types.go
> +// +kubebuilder:validation:Enum=primary;standby;stats;dashboard;secondary
`type ServiceAlias string` is a common type. mssqlserver is not using standby

2024-10-17 12:30 UTC, ArnobKumarSaha approved these changes

2024-10-17 12:31 UTC, merged