security-context for pgbouncer
kubedb/apimachinery pull request #1339
Opened 2024-11-01 10:29 UTC by HiranmoyChowdhury

Signed-off-by: Hiranmoy Das Chowdhury <hiranmoy@appscode.com>

2024-11-05 10:39 UTC, pritamdas99 approved these changes
LGTM!

2025-02-11 13:51 UTC, ArnobKumarSaha requested changes

2025-02-11 13:51 UTC, ArnobKumarSaha commented on apis/kubedb/v1/pgbouncer_helpers.go
> +	// that's why we need to set RunAsUser and RunAsGroup 70
remove.

2025-02-11 13:51 UTC, ArnobKumarSaha commented on apis/kubedb/v1/pgbouncer_helpers.go
> +		if p.Spec.PodTemplate.Spec.SecurityContext == nil || p.Spec.PodTemplate.Spec.SecurityContext.RunAsUser == nil {
https://github.com/kubedb/apimachinery/blob/5c754b01ec0df26596f3e66c8114814b037febe1/apis/kubedb/v1/postgres_helpers.go#L386

2025-02-14 05:47 UTC, ArnobKumarSaha approved these changes

2025-02-14 05:47 UTC, merged