added database image in elasticsearch_version_types
kubedb/apimachinery pull request #824
Opened 2021-11-23 12:22 UTC by raihankhan

2022-01-20 09:22 UTC, kamolhasan requested changes
Perform `make gen fmt`, and push again.

2022-01-20 12:30 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_helpers.go
> +	phase = DashboardPhaseProvisioning
phase := DashboardPhaseProvisioning

2022-01-20 12:32 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_helpers.go
> +	if kmapi.IsConditionFalse(ed.Status.Conditions, string(DashboardConditionAcceptingConnection)) &&
Check, !True() istead of isFalse()

2022-01-20 12:51 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_helpers.go
> +func (ed *ElasticsearchDashboard) GetPhaseFromCondition() DashboardPhase {
Move this function to `pkg/phase`. Make it generic for all Dashboards.

2022-01-21 05:43 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_webhook.go
> +	if len(ed.Name) == validation.DNS1035LabelMaxLength-13 {
Give this responsibility to k8s itself

2022-01-21 05:48 UTC, kamolhasan commented on pkg/phase/phase.go
> +
if !IsConditionTrue(Provisioned){
return provisioning 
}

if !IsConditionTrue(AcceptingConnection){
return NotReady
}

if

2022-01-21 06:18 UTC, raihankhan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_webhook.go
> +	if len(ed.Name) == validation.DNS1035LabelMaxLength-13 {
done

2022-01-21 06:25 UTC, raihankhan commented on pkg/phase/phase.go
> +
done

2022-01-21 08:46 UTC, kamolhasan submitted a review, later dismissed
LGTM!

2022-01-21 09:38 UTC, raihankhan reviewed
ok

2022-01-21 10:24 UTC, kamolhasan approved these changes
LGTM!

2022-01-21 10:26 UTC, merged