add helpers and constants for config merger
kubedb/apimachinery pull request #860
Opened 2022-02-08 12:25 UTC by raihankhan

Signed-off-by: raihankhan <raihan@appscode.com>

2022-02-17 12:47 UTC, kamolhasan requested changes

2022-02-17 12:47 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_helpers.go
> +func (ed *ElasticsearchDashboard) CertificateName(alias ElasticsearchDashboardSecretAlias) string {
CertificateName() --> CertificateSecretName()

2022-02-17 12:47 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_helpers.go
> +func (ed *ElasticsearchDashboard) CertificateName(alias ElasticsearchDashboardSecretAlias) string {
Keep `ElasticsearchDashboardCertificateAlias` as input params

2022-02-17 12:47 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_helpers.go
> +func (ed *ElasticsearchDashboard) CertificateName(alias ElasticsearchDashboardSecretAlias) string {
ElasticsearchDashboardConfigAlias = `operator`, `user`

```
GetConfigSecretName(alias) string{
 if alias== operator{
 	return  util.Namewithsuffix(ed.name, "config")
 } 
 
 if ed.spec.configsecret.name!=nil {
 return ed.spec.configsecret.name
} 
return  util.Namewithsuffix(ed.name, "user-config")
}
```

2022-02-17 12:47 UTC, kamolhasan commented on apis/dashboard/v1alpha1/types.go
> +	CustomConfig            DashboardVolumeName = "dashboard-custom-config"
Start with prefix `DashboardVolume....`

2022-02-18 05:10 UTC, raihankhan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_helpers.go
> +func (ed *ElasticsearchDashboard) CertificateName(alias ElasticsearchDashboardSecretAlias) string {
fixed

2022-02-18 05:10 UTC, raihankhan commented on apis/dashboard/v1alpha1/types.go
> +	CustomConfig            DashboardVolumeName = "dashboard-custom-config"
fixed

2022-02-18 07:17 UTC, kamolhasan approved these changes
LGTM!

2022-02-18 09:17 UTC, merged