Add Support for Opensearch Dashboards
kubedb/apimachinery pull request #878
Opened 2022-03-18 05:14 UTC by raihankhan

Signed-off-by: raihankhan <raihan@appscode.com>

2022-03-21 06:04 UTC, kamolhasan requested changes

2022-03-21 06:04 UTC, kamolhasan commented on apis/dashboard/v1alpha1/types.go
> +	DashboardVolumeKibanaServer               DashboardVolumeName = "kibana-server"
"server-tls"

2022-03-21 06:04 UTC, kamolhasan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_types.go
> -const (
Keep them here.

2022-03-24 08:34 UTC, raihankhan commented on apis/dashboard/v1alpha1/elasticsearchdashboard_types.go
> -const (
re-added the constants here

2022-03-28 11:28 UTC, raihankhan commented on apis/dashboard/v1alpha1/types.go
> +	DashboardVolumeKibanaServer               DashboardVolumeName = "kibana-server"
renamed

2022-03-31 08:50 UTC, kamolhasan submitted a review, later dismissed
LGTM!

2022-03-31 09:04 UTC, kamolhasan approved these changes

2022-03-31 09:14 UTC, kamolhasan approved these changes

2022-03-31 09:39 UTC, merged