update proxysql
kubedb/apimachinery pull request #883
Opened 2022-04-08 10:17 UTC by TasdidurRahman

Signed-off-by: TasdidurRahman <tasdid@appscode.com>

2022-04-18 08:46 UTC, spectro30 requested changes

2022-04-18 08:46 UTC, spectro30 commented on apis/kubedb/v1alpha2/proxysql_types.go
>  	ProxySQLArchiverCert        ProxySQLCertificateAlias = "archiver"
remove `ProxySQLArchiverCert`.

2022-04-18 09:17 UTC, TasdidurRahman commented on apis/kubedb/v1alpha2/proxysql_types.go
>  	ProxySQLArchiverCert        ProxySQLCertificateAlias = "archiver"
done

2022-04-18 09:19 UTC, spectro30 submitted a review, later dismissed
LGTM

2022-04-26 05:14 UTC, spectro30 approved these changes
LGTM

2022-04-26 05:17 UTC, merged