Change MemoryStorage design & Add opsReqOpts in MongoAutoscaler
kubedb/apimachinery pull request #934
Opened 2022-07-19 12:28 UTC by ArnobKumarSaha

Signed-off-by: Arnob kumar saha <arnob@appscode.com>

2022-07-19 12:34 UTC, faem commented on apis/autoscaling/v1alpha1/constants.go
> +	ApplyOptionsAlways  = "ApplyAlways"
ApplyOptionsIfReady ApplyOptions = "ApplyIfReady"
ApplyOptionsAlways ApplyOptions = "ApplyAlways"

2022-07-22 06:00 UTC, faem requested changes

2022-07-27 04:43 UTC, tamalsaha commented on apis/autoscaling/v1alpha1/mongodb_types.go
> +	OpsReqOptions *MongoDBOpsRequestOptions `json:"opsReqOptions,omitempty"`
We should use full words `opsRequestOptions`

2022-07-27 04:43 UTC, tamalsaha commented on apis/autoscaling/v1alpha1/type.go
> +	ScalingThresholdPercentage int32 `json:"scalingThresholdPercentage,omitempty"`
`scalingFactorPercentage` ?

2022-07-27 04:43 UTC, tamalsaha commented on apis/ops/v1alpha1/constant.go
> +)
Needs a proper enum. Also, just use `IfReady` and `Always`

2022-07-27 04:43 UTC, tamalsaha commented on apis/ops/v1alpha1/mongodb_ops_types.go
> +	ApplyOptions *ApplyOptions `json:"applyOptions,omitempty"`
`Default is `ApplyIfReady``

This should not be a pointer. Just use default value.

2022-07-27 04:43 UTC, tamalsaha commented on apis/ops/v1alpha1/type.go
> +type ApplyOptions string
The constants should be moved here right after the type declaration.

2022-07-27 04:43 UTC, tamalsaha commented on apis/autoscaling/v1alpha1/type.go
> +	MemoryStorage *ComputeMemoryStorageSpec `json:"memoryStorage,omitempty"`
`inMemoryStorage` sounds good to me.

2022-07-27 05:50 UTC, tamalsaha requested changes

2022-07-27 05:50 UTC, tamalsaha commented on apis/ops/v1alpha1/type.go
> +// +kubebuilder:default:="IfReady"
`// +kubebuilder:default:="IfReady"` has to be at site this type is used.

2022-07-27 05:50 UTC, tamalsaha commented on apis/autoscaling/v1alpha1/mongodb_types.go
> +	ApplyOption opsapi.ApplyOption `json:"applyOption,omitempty"`
Add `// +kubebuilder:default:="IfReady"` here

```
Apply opsapi.ApplyOption `json:"apply,omitempty"`
```

2022-07-27 07:09 UTC, tamalsaha approved these changes

2022-07-27 07:22 UTC, faem requested changes

2022-07-27 07:22 UTC, faem commented on apis/autoscaling/v1alpha1/type.go
> +	ScalingFactorPercentage int32 `json:"scalingFactorPercentage,omitempty"`
ignore `inMemorySizeGB` in comment

2022-07-27 07:22 UTC, faem commented on apis/autoscaling/v1alpha1/webhook_helpers.go
> +		computeSpec.InMemoryStorage.ScalingFactorPercentage = DefaultInmemoryScalingThreshold
may be rename the constants.

2022-07-27 07:38 UTC, faem submitted a review, later dismissed

2022-07-27 08:37 UTC, faem approved these changes

2022-07-27 08:37 UTC, tamalsaha approved these changes

2022-07-27 08:38 UTC, merged